// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// nip_pca_comp_rcpp
Rcpp::List nip_pca_comp_rcpp(Eigen::MatrixXd X);
RcppExport SEXP _metabom8_nip_pca_comp_rcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(nip_pca_comp_rcpp(X));
    return rcpp_result_gen;
END_RCPP
}
// multiY_Tw_rcpp
Eigen::MatrixXd multiY_Tw_rcpp(Eigen::MatrixXd X, Eigen::MatrixXd Y);
RcppExport SEXP _metabom8_multiY_Tw_rcpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(multiY_Tw_rcpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// nip_PLS_comp_rcpp
Rcpp::List nip_PLS_comp_rcpp(Eigen::MatrixXd X, Eigen::MatrixXd Y);
RcppExport SEXP _metabom8_nip_PLS_comp_rcpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(nip_PLS_comp_rcpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// ortho_gram_schmidt_rcpp
Eigen::MatrixXd ortho_gram_schmidt_rcpp(Eigen::MatrixXd u, Eigen::MatrixXd v);
RcppExport SEXP _metabom8_ortho_gram_schmidt_rcpp(SEXP uSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type u(uSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(ortho_gram_schmidt_rcpp(u, v));
    return rcpp_result_gen;
END_RCPP
}
// nip_opls_rcpp
Rcpp::List nip_opls_rcpp(Eigen::MatrixXd X, Eigen::MatrixXd Y);
RcppExport SEXP _metabom8_nip_opls_rcpp(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(nip_opls_rcpp(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// tss_rcpp
Rcpp::NumericVector tss_rcpp(Eigen::MatrixXd X);
RcppExport SEXP _metabom8_tss_rcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(tss_rcpp(X));
    return rcpp_result_gen;
END_RCPP
}
// opls_pred_rcpp
Rcpp::List opls_pred_rcpp(Rcpp::List opls_mod, Rcpp::List pred_mod, Eigen::MatrixXd Xnew);
RcppExport SEXP _metabom8_opls_pred_rcpp(SEXP opls_modSEXP, SEXP pred_modSEXP, SEXP XnewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type opls_mod(opls_modSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type pred_mod(pred_modSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Xnew(XnewSEXP);
    rcpp_result_gen = Rcpp::wrap(opls_pred_rcpp(opls_mod, pred_mod, Xnew));
    return rcpp_result_gen;
END_RCPP
}
// pls_pred_rcpp
Rcpp::List pls_pred_rcpp(Rcpp::List pls_mod, Eigen::MatrixXd Xnew);
RcppExport SEXP _metabom8_pls_pred_rcpp(SEXP pls_modSEXP, SEXP XnewSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type pls_mod(pls_modSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Xnew(XnewSEXP);
    rcpp_result_gen = Rcpp::wrap(pls_pred_rcpp(pls_mod, Xnew));
    return rcpp_result_gen;
END_RCPP
}
// sd_rcpp
List sd_rcpp(NumericMatrix X);
RcppExport SEXP _metabom8_sd_rcpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(sd_rcpp(X));
    return rcpp_result_gen;
END_RCPP
}
// scale_rcpp
List scale_rcpp(NumericMatrix X, IntegerVector idc, bool center, int scale_type);
RcppExport SEXP _metabom8_scale_rcpp(SEXP XSEXP, SEXP idcSEXP, SEXP centerSEXP, SEXP scale_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idc(idcSEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< int >::type scale_type(scale_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_rcpp(X, idc, center, scale_type));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metabom8_nip_pca_comp_rcpp", (DL_FUNC) &_metabom8_nip_pca_comp_rcpp, 1},
    {"_metabom8_multiY_Tw_rcpp", (DL_FUNC) &_metabom8_multiY_Tw_rcpp, 2},
    {"_metabom8_nip_PLS_comp_rcpp", (DL_FUNC) &_metabom8_nip_PLS_comp_rcpp, 2},
    {"_metabom8_ortho_gram_schmidt_rcpp", (DL_FUNC) &_metabom8_ortho_gram_schmidt_rcpp, 2},
    {"_metabom8_nip_opls_rcpp", (DL_FUNC) &_metabom8_nip_opls_rcpp, 2},
    {"_metabom8_tss_rcpp", (DL_FUNC) &_metabom8_tss_rcpp, 1},
    {"_metabom8_opls_pred_rcpp", (DL_FUNC) &_metabom8_opls_pred_rcpp, 3},
    {"_metabom8_pls_pred_rcpp", (DL_FUNC) &_metabom8_pls_pred_rcpp, 2},
    {"_metabom8_sd_rcpp", (DL_FUNC) &_metabom8_sd_rcpp, 1},
    {"_metabom8_scale_rcpp", (DL_FUNC) &_metabom8_scale_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_metabom8(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
