#' @title Cross-validated ANOVA for O-PLS models
#' @description
#' Performs a cross-validated ANOVA (CV-ANOVA) test for OPLS models. The function compares residuals from a null model and a model using cross-validated predictive scores to assess the significance of the OPLS model.
#'
#' @param smod An object of class \code{OPLS_metabom8}, generated by functions in the \pkg{metabom8} package.
#'
#' @details
#' CV-ANOVA formally compares the fit of two linear models using the size of their residuals.
#' The null model regresses the response on an intercept only:
#' \deqn{Y_i = \beta_0 + \epsilon_i}
#' The full model includes the cross-validated predictive scores:
#' \deqn{Y_i = \beta_0 + \beta_1 t_{\text{pred},i} + \epsilon_i}
#' Here, \eqn{Y_i} is the response for observation \eqn{i}, \eqn{t_{\text{pred},i}} the cross-validated predictive score, and \eqn{\epsilon_i} are residuals.
#' The residual sums of squares (SS) and degrees of freedom (DF) from both models are used to calculate an F-statistic and associated p-value to assess if the OPLS model significantly improves the fit.
#'
#' Please note: larger sample sizes increase the power to detect true effects. With few samples, even strong models may not reach statistical significance.
#'
#' @return A \code{data.frame} containing:
#' \itemize{
#'   \item \code{SS} - Sum of Squares
#'   \item \code{DF} - Degrees of Freedom
#'   \item \code{MS} - Mean Squares
#'   \item \code{F_value} - F statistic
#'   \item \code{p_value} - P-value from the F-test
#' }
#'
#' @references
#' Eriksson, L., et al. (2008). CV-ANOVA for significance testing of PLS and OPLS models. \emph{Journal of Chemometrics}, 22(11-12), 594–600.
#'
#' @seealso \code{\link{opls}}, \code{\link{dmodx}}
#'
#' @examples
#' data("covid")
#' X <- covid$X
#' an <- covid$an
#' mod <- opls(X, an$type)
#' cvanova(mod)
#'
#' # Internally, two linear models are fitted:
#' # Null model: lm(Y ~ 1)
#' # Full model: lm(Y ~ 1 + t_pred_cv)
#' #
#' # where Y is the response variable and t_pred_cv the cross-validated predictive scores.
#'
#' @family NMR
#' @export
#' @importFrom stats lm pf
cvanova <- function(smod) {
  if (!inherits(smod, "OPLS_metabom8")) {
    stop("Function requires an object of class 'OPLS_metabom8'.")
  }

  df_total <- nrow(smod@Y$dummy) - 1
  df_reg <- smod@nPC * 2
  df_res <- df_total - df_reg

  lm_null <- lm(smod@Y$dummy[, 1] ~ 1)
  res_null <- lm_null$residuals

  lm_model <- lm(smod@Y$dummy[, 1] ~ 1 + smod@t_pred_cv[, 1])
  res_model <- lm_model$residuals

  ss_total <- sum(res_null^2)
  ss_reg <- sum(res_model^2)
  ss_res <- ss_total - ss_reg

  ms_total <- ss_total / df_total
  ms_reg <- ss_reg / df_reg
  ms_res <- ss_res / df_res

  F_val <- ms_reg / ms_res
  p_val <- 1 - pf(F_val, df_reg, df_res)

  result <- data.frame(
    SS = c(format(c(ss_total, ss_reg, ss_res), scientific = TRUE), NA),
    DF = c(df_total, df_reg, df_res, NA),
    MS = c(format(c(ms_total, ms_reg, ms_res), scientific = TRUE), NA),
    F_value = c(NA, NA, NA, F_val),
    p_value = c(NA, NA, NA, format(p_val, scientific = TRUE)),
    row.names = c("Total corrected", "Regression", "Residual", "RESULT")
  )

  return(result)
}
