# R CMD check workflow for an R package (Ubuntu, macOS, Windows)
# Includes R versions 3.6.3 through 4.5.1 (latest release as of July 2025:contentReference[oaicite:3]{index=3})
# Installs dependencies with caching and uploads check logs on failure.

name: R-CMD-check
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['3.6.3', '4.0.5', '4.5.1']
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    steps:
      - uses: actions/checkout@v3

      # Set up Pandoc (needed for building vignettes, etc.)
      - uses: r-lib/actions/setup-pandoc@v2

      # Set up R on the runner (install specific R version, and Rtools on Windows)
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true  # Use RStudio Package Manager on Linux for binaries:contentReference[oaicite:4]{index=4}

      # Install package dependencies (with caching) and additional tools
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2               # Bump to refresh cache if needed:contentReference[oaicite:5]{index=5}
          extra-packages: rcmdcheck      # Install rcmdcheck for running checks

      # Run R CMD check (as CRAN, skipping manual/doc build for speed)
      - name: Run R CMD check
        run: |
          R CMD build .
          R CMD check *.tar.gz --no-manual --as-cran

      # If any errors or failures occurred, upload the check artifacts (logs, etc.)
      - name: Upload check artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.os }}-R${{ matrix.r }}-check-artifacts"
          path: "*.Rcheck/**"
