
on:
  push:
    branches: [dev]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_KEEP_PKG_SOURCE: yes
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Ensure UTF-8 locale (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen en_US.UTF-8
          sudo update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

      - name: Force UTF-8 + cairo on macOS
        if: runner.os == 'macOS'
        run: |
          echo 'Sys.setlocale("LC_ALL", "en_US.UTF-8")' >> ~/.Rprofile
          echo 'options(encoding = "UTF-8")' >> ~/.Rprofile
          echo 'options(bitmapType = "cairo")' >> ~/.Rprofile
          # Helpful to confirm in logs:
          echo 'print(Sys.getlocale()); print(l10n_info())' >> ~/.Rprofile
          
      - name: Install nmrData from GitHub
        run: Rscript -e 'if (!requireNamespace("remotes", quietly=TRUE)) install.packages("remotes"); remotes::install_github("tkimhofer/nmrData")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
