
name: R-CMD-check

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['4.3', '4.2', '4.1.1']

    steps:
      - uses: actions/checkout@v4

      - name: Install Pandoc on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install Pandoc on macOS
        if: runner.os == 'macOS'
        run: brew install pandoc

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install CRAN dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "testthat", "knitr", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install suggest from GH
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          remotes::install_github("tkimhofer/nmrdata")
        shell: Rscript {0}

      - name: List installed packages
        run: Rscript -e 'installed.packages()[, "Package"]'

      - name: Run tests
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--run-donttest", "--no-build-vignettes"), error_on = "error")
          devtools::test()
        shell: Rscript {0}

